Configuration/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name='home'),
    path('spp/', include('spp.urls')),
    path('petugas/', include('petugas.urls')),
    path('kelas/', include('kelas.urls')),
    path('user/', include('user.urls')),
    path('siswa/', include('siswa.urls')),
    path('pembayaran/', include('pembayaran.urls')),    
    path('history_pembayaran/', include('history_pembayaran.urls')),

]

kelas/urls.py
from django.urls import path
from . import views

app_name = 'kelas'

urlpatterns = [
    path('', views.daftar_kelas, name='daftar_kelas'),
    path('tambah/', views.tambah_kelas, name='tambah_kelas'),
    path('<int:kelas_id>/', views.detail_kelas, name='detail_kelas'),
    path('<int:kelas_id>/edit/', views.edit_kelas, name='edit_kelas'),
    path('<int:kelas_id>/hapus/', views.hapus_kelas, name='hapus_kelas'),
]

pembayaran/urls.py
from django.urls import path
from . import views


app_name = 'pembayaran'

urlpatterns = [
    path('', views.daftar_pembayaran, name='daftar_pembayaran'),
    path('tambah/', views.tambah_pembayaran, name='tambah_pembayaran'),
    path('cetak/<int:pembayaran_id>/', views.cetak_pembayaran, name='cetak_pembayaran'),
    path('<int:pembayaran_id>/', views.detail_pembayaran, name='detail_pembayaran'),
    path('<int:pembayaran_id>/edit/', views.edit_pembayaran, name='edit_pembayaran'),
    path('<int:pembayaran_id>/hapus/', views.hapus_pembayaran, name='hapus_pembayaran'),

]

petugas/urls.py
from django.urls import path
from . import views

app_name = 'petugas'  # nama aplkasi

urlpatterns = [
    path('', views.daftar_petugas, name='daftar_petugas'),
    path('tambah/', views.tambah_petugas, name='tambah_petugas'),
    path('<int:petugas_id>/', views.detail_petugas, name='detail_petugas'),
    path('<int:petugas_id>/edit/', views.edit_petugas, name='edit_petugas'),
    path('<int:petugas_id>/hapus/', views.hapus_petugas, name='hapus_petugas'),
]

siswa/urls.py
from django.urls import path
from . import views

app_name = 'siswa'

urlpatterns = [
    path('', views.daftar_siswa, name='daftar_siswa'),
    path('tambah/', views.tambah_siswa, name='tambah_siswa'),
    path('<str:nisn>/', views.detail_siswa, name='detail_siswa'),
    path('<str:nisn>/edit/', views.edit_siswa, name='edit_siswa'),
    path('<str:nisn>/hapus/', views.hapus_siswa, name='hapus_siswa'),
]

spp/urls.py
from django.urls import path
from . import views

app_name = 'spp'  # nama aplkasi

urlpatterns = [
    path('', views.daftar_spp, name='daftar_spp'),
    path('tambah/', views.tambah_spp, name='tambah_spp'),
    path('spp/<int:spp_id>/', views.detail_spp, name='detail_spp'),
    path('<int:spp_id>/edit/', views.edit_spp, name='edit_spp'),
    path('<int:spp_id>/hapus/', views.hapus_spp, name='hapus_spp'),
]

templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SPP | Smk Merdeka Bandung</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %} ">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition sidebar-mini sidebar-collapse">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light" style="background-color: #ba67bd;">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home' %}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color: #661169">
    <!-- Brand Logo -->
    <a href="{% url 'home' %}" class="brand-link">
      <img src="{% static 'dist/img/logo_sekolah.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">SPP</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            {% if user.is_authenticated %}
                <a href="#" class="d-block">{{ user.username }}</a>
            {% else %}
                <a href="#" class="d-block">Guest</a>
            {% endif %}
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Data
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'siswa:daftar_siswa' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Data Siswa</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'kelas:daftar_kelas' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Data Kelas</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'petugas:daftar_petugas' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Data Petugas</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'spp:daftar_spp' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Data SPP</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{% url 'pembayaran:daftar_pembayaran' %}" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Pembayaran
                        <span class="right badge badge-danger">New</span>
                    </p>
                </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'history_pembayaran:history_pembayaran' %}" class="nav-link">
                  <i class="nav-icon fas fa-history"></i>
                  <p>
                      History Pembayaran
                  </p>
              </a>
            </li>
            <li class="nav-item">
              <form id="logout-form" action="{% url 'user_logout' %}" method="post" style="display: none;">
                  {% csrf_token %}
              </form>
              <a href="#" class="nav-link" onclick="document.getElementById('logout-form').submit();">
                  <i class="nav-icon fas fa-sign-out-alt"></i>
                  <p>Logout</p>
              </a>
          </li>                           
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>{% block content_header %}{% endblock %}</h1>
              </div>
            </div>
          </div>
        </section>
  
        <!-- Main content -->
        <section class="content">
          {% block main_content %}{% endblock %}
        </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->



  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base_generic.html' %}

{% block content_header %}
  Dashboard
{% endblock %}

{% block main_content %}
  <!-- Main content -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Welcome to the Dashboard</h5>
            <p class="card-text">This is the main content area of your dashboard. You can customize it based on your requirements.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container-fluid -->
{% endblock %}